#:schema node_modules/wrangler/config-schema.json
name = "depd"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-02"
send_metrics = false

[dev]
port = 8080

[placement]
mode = "smart"

[vars]
NODE_VERSION = "20"
PNPM_VERSION = "9"

[env.production.vars]
NODE_VERSION = "20"
PNPM_VERSION = "9"
